import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { getImage } from '../../lib/fetch-images'

function ImagePage({ image, id }) {
    let title=`Image #${id}`;

    return (
        <div>
            <Head>
                <title>{title}</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Link href='/'>
                🔙 Return
            </Link>
            <main>
                <h1 className="text-center text-2xl font-bold">{title}</h1>
                <div className="flex items-center justify-center mt-10">
                    <Image
                        className="rounded-md overflow-hidden"
                        src={image.src.large}
                        alt={image.alt}
                        height={600}
                        width={600}
                    ></Image>
                </div>
                <div className="mt-10 mx-20 text-center">{image.alt}</div>
            </main>
        </div>
    )
}

export async function getServerSideProps(context) {
    const image = await getImage(context.query.id);

    return { 
        props: {
            image,
            id: context.query.id,
        },
    }
}

export default ImagePage