import Head from 'next/head'
import Searchbar from '../../components/searchbar'
import Gallery from '../../components/gallery'
import { getSearchResults } from '../../lib/fetch-images'

function ImagePage({ images, query }) {
  let title=`Image search for ${query}`;

  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="text-center text-2xl font-bold mt-3">{title}</h1>
        <Searchbar/>
        <Gallery images={images}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  const data = await getSearchResults(context.query['search-terms']);

  return { 
    props: {
      images: data.photos,
      query: context.query['search-terms']
    },
  }
}

export default ImagePage