import Head from 'next/head'
import Searchbar from '../components/searchbar'
import Gallery from '../components/gallery'
import { getInitialImages } from '../lib/fetch-images'

export default function Home({data}) {
  let images = data.photos;

  return (
    <div>
      <Head>
        <title>Image search app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex flex-col items-center">
        <h1 className="text-center text-2xl font-bold mt-3">Image search app</h1>
        <Searchbar/>
        <Gallery images={images}/>
      </main>
    </div>
  )
}

export async function getServerSideProps(context) {
  let data = await getInitialImages();

  return { 
    props: {
        data
    },
  }
}